version: "3.8"

services:
  redis:
    image: redis:latest # :latest 태그(명시하지 않아도 default 값)는 가장 최신 안정 버전을 의미함(redis:6.2.6는 redis 6.2.6 버전을 의미)
    ports:
      - 6379:6379

  spring_boot:
    image: devhub
    build: .
    expose:
      - 8080 # 컨테이너 내부에서만 해당 포트를 인식하게끔 하는 속성. 즉, 다른 컨테이너에서는 8080으로 통신이 가능하지만, 외부에서는 8080으로 접근할 수 없음
    volumes:
      - /data/DevHubProject:/data/DevHubProject # ubuntu
    depends_on:
      - redis  # redis 컨테이너가 먼저 올라간 다음 nginx가 올라가도록 설정

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d # nginx/conf.d 폴더를 컨테이너 내부의 /etc/nginx/conf.d로 마운트
    depends_on:
      - spring_boot