"""Add new fields to User model

Revision ID: bfb38e504f5c
Revises: 
Create Date: 2024-07-14 14:14:23.104388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfb38e504f5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('save_file', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('differences',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('role_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('delete_condition', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('delete_condition')
        batch_op.drop_column('role_type')
        batch_op.drop_column('email')

    with op.batch_alter_table('save_file', schema=None) as batch_op:
        batch_op.alter_column('differences',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
